import type { Category } from '../types/category.types';

export const DEFAULT_CATEGORIES: readonly Category[] = [
  {
    id: 1,
    name: 'Development',
    color: '#0066FF',
    productivityScore: 2,
    icon: 'code',
    isDefault: true,
  },
  {
    id: 2,
    name: 'Productivity',
    color: '#10B981',
    productivityScore: 2,
    icon: 'check-circle',
    isDefault: true,
  },
  {
    id: 3,
    name: 'Education',
    color: '#6366F1',
    productivityScore: 1,
    icon: 'book-open',
    isDefault: true,
  },
  {
    id: 4,
    name: 'Communication',
    color: '#0EA5E9',
    productivityScore: 0,
    icon: 'message-square',
    isDefault: true,
  },
  { id: 5, name: 'Design', color: '#EC4899', productivityScore: 1, icon: 'figma', isDefault: true },
  {
    id: 6,
    name: 'Finance',
    color: '#059669',
    productivityScore: 0,
    icon: 'dollar-sign',
    isDefault: true,
  },
  {
    id: 7,
    name: 'Health & Fitness',
    color: '#14B8A6',
    productivityScore: 1,
    icon: 'activity',
    isDefault: true,
  },
  {
    id: 8,
    name: 'News & Reference',
    color: '#F59E0B',
    productivityScore: -1,
    icon: 'newspaper',
    isDefault: true,
  },
  {
    id: 9,
    name: 'Shopping',
    color: '#8B5CF6',
    productivityScore: -1,
    icon: 'shopping-bag',
    isDefault: true,
  },
  {
    id: 10,
    name: 'Social Media',
    color: '#EF4444',
    productivityScore: -2,
    icon: 'share-2',
    isDefault: true,
  },
  {
    id: 11,
    name: 'Entertainment',
    color: '#F97316',
    productivityScore: -2,
    icon: 'film',
    isDefault: true,
  },
  { id: 12, name: 'Other', color: '#6B7280', productivityScore: 0, icon: 'globe', isDefault: true },
] as const;
